spring:
  dubbo:
    name: order-service-consumer
    owner: xuxl
    address: zookeeper://127.0.0.1:2181
  redis:
    host: 192.168.12.252
    port: 3000
    timeout: 3000
    pool:
      max-active: 8
